# 
# Docker Compose YAML
# 
# See https://docs.docker.com/compose/compose-file/
# for more details
# 

version: "3"

services:
  database:
    # Simple database service
    # https://hub.docker.com/_/mysql/
    #
    # And some examples
    # https://stackoverflow.com/questions/39175194/docker-compose-persistent-data-mysql
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootable
      MYSQL_USER: user
      MYSQL_PASS: password
      MYSQL_DATABASE: mice
    volumes:
      - ./data:/var/lib/mysql
  webapp:
    build: ./webapp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 10s
      retries: 3
      #start_period: 1m
    ports:
      - "8080:8080"

  mouse:
    build: ./mouse
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - './mouse/src:/usr/src/app/src'
    ports:
      - '3000:3000'

